#############################################################################
# Makefile for building: TwineHeadlessBrowser
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Jul 1 22:18:27 2013
# Project:  TwineHeadlessBrowser.pro
# Template: app
# Command: /home/jduren/projects/TwineHeadlessBrowser/qt/bin/qmake -o Makefile TwineHeadlessBrowser.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../phantomjs/src/qt/mkspecs/linux-g++-64 -I. -I../phantomjs/src/qt/include/QtCore -I../phantomjs/src/qt/include/QtGui -I../phantomjs/src/qt/include/QtWebKit -I../phantomjs/src/qt/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/jduren/projects/phantomjs/src/qt/lib
LIBS          = $(SUBLIBS)  -L/home/jduren/projects/phantomjs/src/qt/lib -lQtWebKit -L/home/jduren/projects/phantomjs/src/qt/lib -lQtNetwork -lQtGui -lfreetype -lfontconfig -lQtCore -lm -ldl -lrt -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/jduren/projects/TwineHeadlessBrowser/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qcommandline.cpp \
		commandparser.cpp \
		pageloader.cpp moc_qcommandline.cpp \
		moc_commandparser.cpp \
		moc_pageloader.cpp
OBJECTS       = main.o \
		qcommandline.o \
		commandparser.o \
		pageloader.o \
		moc_qcommandline.o \
		moc_commandparser.o \
		moc_pageloader.o
DIST          = ../phantomjs/src/qt/mkspecs/common/unix.conf \
		../phantomjs/src/qt/mkspecs/common/linux.conf \
		../phantomjs/src/qt/mkspecs/common/gcc-base.conf \
		../phantomjs/src/qt/mkspecs/common/gcc-base-unix.conf \
		../phantomjs/src/qt/mkspecs/common/g++-base.conf \
		../phantomjs/src/qt/mkspecs/common/g++-unix.conf \
		../phantomjs/src/qt/mkspecs/qconfig.pri \
		../phantomjs/src/qt/mkspecs/modules/qt_webkit_version.pri \
		../phantomjs/src/qt/mkspecs/features/qt_functions.prf \
		../phantomjs/src/qt/mkspecs/features/qt_config.prf \
		../phantomjs/src/qt/mkspecs/features/exclusive_builds.prf \
		../phantomjs/src/qt/mkspecs/features/default_pre.prf \
		../phantomjs/src/qt/mkspecs/features/release.prf \
		../phantomjs/src/qt/mkspecs/features/default_post.prf \
		../phantomjs/src/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		../phantomjs/src/qt/mkspecs/features/warn_on.prf \
		../phantomjs/src/qt/mkspecs/features/qt.prf \
		../phantomjs/src/qt/mkspecs/features/unix/thread.prf \
		../phantomjs/src/qt/mkspecs/features/moc.prf \
		../phantomjs/src/qt/mkspecs/features/resources.prf \
		../phantomjs/src/qt/mkspecs/features/uic.prf \
		../phantomjs/src/qt/mkspecs/features/yacc.prf \
		../phantomjs/src/qt/mkspecs/features/lex.prf \
		../phantomjs/src/qt/mkspecs/features/include_source_dir.prf \
		TwineHeadlessBrowser.pro
QMAKE_TARGET  = TwineHeadlessBrowser
DESTDIR       = 
TARGET        = TwineHeadlessBrowser

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TwineHeadlessBrowser.pro  ../phantomjs/src/qt/mkspecs/linux-g++-64/qmake.conf ../phantomjs/src/qt/mkspecs/common/unix.conf \
		../phantomjs/src/qt/mkspecs/common/linux.conf \
		../phantomjs/src/qt/mkspecs/common/gcc-base.conf \
		../phantomjs/src/qt/mkspecs/common/gcc-base-unix.conf \
		../phantomjs/src/qt/mkspecs/common/g++-base.conf \
		../phantomjs/src/qt/mkspecs/common/g++-unix.conf \
		../phantomjs/src/qt/mkspecs/qconfig.pri \
		../phantomjs/src/qt/mkspecs/modules/qt_webkit_version.pri \
		../phantomjs/src/qt/mkspecs/features/qt_functions.prf \
		../phantomjs/src/qt/mkspecs/features/qt_config.prf \
		../phantomjs/src/qt/mkspecs/features/exclusive_builds.prf \
		../phantomjs/src/qt/mkspecs/features/default_pre.prf \
		../phantomjs/src/qt/mkspecs/features/release.prf \
		../phantomjs/src/qt/mkspecs/features/default_post.prf \
		../phantomjs/src/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		../phantomjs/src/qt/mkspecs/features/warn_on.prf \
		../phantomjs/src/qt/mkspecs/features/qt.prf \
		../phantomjs/src/qt/mkspecs/features/unix/thread.prf \
		../phantomjs/src/qt/mkspecs/features/moc.prf \
		../phantomjs/src/qt/mkspecs/features/resources.prf \
		../phantomjs/src/qt/mkspecs/features/uic.prf \
		../phantomjs/src/qt/mkspecs/features/yacc.prf \
		../phantomjs/src/qt/mkspecs/features/lex.prf \
		../phantomjs/src/qt/mkspecs/features/include_source_dir.prf \
		/home/jduren/projects/phantomjs/src/qt/lib/libQtWebKit.prl \
		/home/jduren/projects/phantomjs/src/qt/lib/libQtGui.prl \
		/home/jduren/projects/phantomjs/src/qt/lib/libQtCore.prl \
		/home/jduren/projects/phantomjs/src/qt/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile TwineHeadlessBrowser.pro
../phantomjs/src/qt/mkspecs/common/unix.conf:
../phantomjs/src/qt/mkspecs/common/linux.conf:
../phantomjs/src/qt/mkspecs/common/gcc-base.conf:
../phantomjs/src/qt/mkspecs/common/gcc-base-unix.conf:
../phantomjs/src/qt/mkspecs/common/g++-base.conf:
../phantomjs/src/qt/mkspecs/common/g++-unix.conf:
../phantomjs/src/qt/mkspecs/qconfig.pri:
../phantomjs/src/qt/mkspecs/modules/qt_webkit_version.pri:
../phantomjs/src/qt/mkspecs/features/qt_functions.prf:
../phantomjs/src/qt/mkspecs/features/qt_config.prf:
../phantomjs/src/qt/mkspecs/features/exclusive_builds.prf:
../phantomjs/src/qt/mkspecs/features/default_pre.prf:
../phantomjs/src/qt/mkspecs/features/release.prf:
../phantomjs/src/qt/mkspecs/features/default_post.prf:
../phantomjs/src/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
../phantomjs/src/qt/mkspecs/features/warn_on.prf:
../phantomjs/src/qt/mkspecs/features/qt.prf:
../phantomjs/src/qt/mkspecs/features/unix/thread.prf:
../phantomjs/src/qt/mkspecs/features/moc.prf:
../phantomjs/src/qt/mkspecs/features/resources.prf:
../phantomjs/src/qt/mkspecs/features/uic.prf:
../phantomjs/src/qt/mkspecs/features/yacc.prf:
../phantomjs/src/qt/mkspecs/features/lex.prf:
../phantomjs/src/qt/mkspecs/features/include_source_dir.prf:
/home/jduren/projects/phantomjs/src/qt/lib/libQtWebKit.prl:
/home/jduren/projects/phantomjs/src/qt/lib/libQtGui.prl:
/home/jduren/projects/phantomjs/src/qt/lib/libQtCore.prl:
/home/jduren/projects/phantomjs/src/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile TwineHeadlessBrowser.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TwineHeadlessBrowser1.0.0 || $(MKDIR) .tmp/TwineHeadlessBrowser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TwineHeadlessBrowser1.0.0/ && $(COPY_FILE) --parents qcommandline.h commandparser.h pageloader.h .tmp/TwineHeadlessBrowser1.0.0/ && $(COPY_FILE) --parents main.cpp qcommandline.cpp commandparser.cpp pageloader.cpp .tmp/TwineHeadlessBrowser1.0.0/ && (cd `dirname .tmp/TwineHeadlessBrowser1.0.0` && $(TAR) TwineHeadlessBrowser1.0.0.tar TwineHeadlessBrowser1.0.0 && $(COMPRESS) TwineHeadlessBrowser1.0.0.tar) && $(MOVE) `dirname .tmp/TwineHeadlessBrowser1.0.0`/TwineHeadlessBrowser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TwineHeadlessBrowser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qcommandline.cpp moc_commandparser.cpp moc_pageloader.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qcommandline.cpp moc_commandparser.cpp moc_pageloader.cpp
moc_qcommandline.cpp: qcommandline.h
	/home/jduren/projects/phantomjs/src/qt/bin/moc $(DEFINES) $(INCPATH) qcommandline.h -o moc_qcommandline.cpp

moc_commandparser.cpp: qcommandline.h \
		commandparser.h
	/home/jduren/projects/phantomjs/src/qt/bin/moc $(DEFINES) $(INCPATH) commandparser.h -o moc_commandparser.cpp

moc_pageloader.cpp: pageloader.h
	/home/jduren/projects/phantomjs/src/qt/bin/moc $(DEFINES) $(INCPATH) pageloader.h -o moc_pageloader.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp commandparser.h \
		qcommandline.h \
		pageloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qcommandline.o: qcommandline.cpp qcommandline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcommandline.o qcommandline.cpp

commandparser.o: commandparser.cpp commandparser.h \
		qcommandline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandparser.o commandparser.cpp

pageloader.o: pageloader.cpp pageloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pageloader.o pageloader.cpp

moc_qcommandline.o: moc_qcommandline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcommandline.o moc_qcommandline.cpp

moc_commandparser.o: moc_commandparser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commandparser.o moc_commandparser.cpp

moc_pageloader.o: moc_pageloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pageloader.o moc_pageloader.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

